"use client";

import {
  ArrowDown,
  ArrowUp,
  Banknote,
  BarChart3,
  Bell,
  Briefcase,
  Building2,
  CalendarDays,
  CheckCircle2,
  CreditCard,
  Download,
  Edit3,
  GripVertical,
  HandCoins,
  Handshake,
  Home,
  Info,
  LayoutDashboard,
  LineChart,
  PiggyBank,
  Plus,
  Receipt,
  RefreshCw,
  Repeat,
  Search,
  Settings,
  TrendingDown,
  TrendingUp,
  Trash2,
  UserCircle,
  Wallet,
  type LucideIcon,
} from "lucide-react";
import { CircleHelp } from "lucide-react";

const REGISTRY: Record<string, LucideIcon> = {
  account_balance: Building2,
  account_balance_wallet: Wallet,
  account_circle: UserCircle,
  add: Plus,
  apartment: Building2,
  arrow_downward: ArrowDown,
  arrow_upward: ArrowUp,
  calendar_month: CalendarDays,
  check_circle: CheckCircle2,
  credit_card: CreditCard,
  currency_exchange: Repeat,
  dashboard: LayoutDashboard,
  delete: Trash2,
  download: Download,
  drag_indicator: GripVertical,
  edit: Edit3,
  error: Info,
  event: CalendarDays,
  handshake: Handshake,
  help_outline: CircleHelp,
  home: Home,
  info: Info,
  insights: BarChart3,
  money_off: HandCoins,
  notifications: Bell,
  payments: Banknote,
  percent: LineChart,
  receipt_long: Receipt,
  savings: PiggyBank,
  search: Search,
  settings: Settings,
  show_chart: LineChart,
  trending_down: TrendingDown,
  trending_up: TrendingUp,
  undo: RefreshCw,
  work: Briefcase,
};

export function resolveSymbolIcon(name: string): LucideIcon {
  return REGISTRY[name] ?? CircleHelp;
}
